/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.flujos.Formularios;

import com.flujos.DAOs.DAOCheque;
import com.flujos.Entidades.Cheque;
import com.flujos.Utilidades.Conexion;
import com.flujos.Utilidades.Utilidades;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.Date;

/**
 *
 * @author monse
 */
public class FrmCheques extends javax.swing.JFrame {

    private Conexion con;
    private DAOCheque daoCheque;

    /**
     * Creates new form FrmCheques
     */
    public FrmCheques() {
        initComponents();
        inicializar();
    }

    private void inicializar() {

        TxtNumero.setText("");
        TxtImporteCheque.setText("");
        jDateFechaCobro.setDate(null);
        jComboTipoCheque.setSelectedIndex(0);
        jComboEstadoCheque.setSelectedIndex(0);
        TxtObservacionCheque.setText("");
        jDateFechaEntrega.setDate(null);
        jComboTitularCheque.setSelectedIndex(0);
        jComboTitularDestino.setSelectedIndex(0);
        TxtUsoCheque.setText("");
        btnAgregarCheque.setEnabled(true);
        btnModificarCheque.setEnabled(false);
        btnEliminarCheque.setEnabled(false);
        btnLimpiarCheque.setEnabled(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtNumero = new javax.swing.JTextField();
        lblNumCheque = new javax.swing.JLabel();
        lblImporteCheque = new javax.swing.JLabel();
        TxtImporteCheque = new javax.swing.JTextField();
        lblTipoCheque = new javax.swing.JLabel();
        lblEstadoDeCheque = new javax.swing.JLabel();
        lblObservacionCheque = new javax.swing.JLabel();
        TxtObservacionCheque = new javax.swing.JTextField();
        lblFechaEntrega = new javax.swing.JLabel();
        lblFechaCobro = new javax.swing.JLabel();
        lblTitularCheque = new javax.swing.JLabel();
        lblTitularDestino = new javax.swing.JLabel();
        lblUsoCheque = new javax.swing.JLabel();
        TxtUsoCheque = new javax.swing.JTextField();
        jDateFechaCobro = new com.toedter.calendar.JDateChooser();
        jDateFechaEntrega = new com.toedter.calendar.JDateChooser();
        btnAgregarCheque = new javax.swing.JButton();
        btnModificarCheque = new javax.swing.JButton();
        btnEliminarCheque = new javax.swing.JButton();
        btnLimpiarCheque = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        TxtIdCheque = new javax.swing.JTextField();
        jComboEstadoCheque = new javax.swing.JComboBox<>();
        jComboTipoCheque = new javax.swing.JComboBox<>();
        jComboTitularDestino = new javax.swing.JComboBox<>();
        jComboTitularCheque = new javax.swing.JComboBox<>();
        TxtIdTitularCheque = new javax.swing.JTextField();
        TxtIdTitularDestinoCheque = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNumCheque.setText("Numero de cheque:");

        lblImporteCheque.setText("Importe de cheque:");

        lblTipoCheque.setText("Tipo de cheque");

        lblEstadoDeCheque.setText("Estado de cheque:");

        lblObservacionCheque.setText("Observacion del cheque:");

        lblFechaEntrega.setText("Fecha de entrega:");

        lblFechaCobro.setText("Fecha de cobro:");

        lblTitularCheque.setText("Titular del cheque:");

        lblTitularDestino.setText("Titular de destino:");

        lblUsoCheque.setText("Uso de cheque");

        btnAgregarCheque.setText("Agregar");
        btnAgregarCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarChequeActionPerformed(evt);
            }
        });

        btnModificarCheque.setText("Modificar");

        btnEliminarCheque.setText("Eliminar");

        btnLimpiarCheque.setText("Limpiar");

        jButton1.setText("Buscar");

        TxtIdCheque.setEnabled(false);

        jComboEstadoCheque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Cobrado", "Por cobrar" }));

        jComboTipoCheque.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--", "Propio", "Terceros" }));

        TxtIdTitularCheque.setEnabled(false);

        TxtIdTitularDestinoCheque.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(lblNumCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(TxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(lblImporteCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(TxtImporteCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(lblFechaCobro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jDateFechaCobro, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(lblTipoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jComboTipoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(lblEstadoDeCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jComboEstadoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(lblObservacionCheque)
                        .addGap(71, 71, 71)
                        .addComponent(TxtObservacionCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(lblUsoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(TxtUsoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnAgregarCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnModificarCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnEliminarCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(btnLimpiarCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(288, 288, 288)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTitularCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDateFechaEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(jComboTitularCheque, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(lblTitularDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(jComboTitularDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtIdTitularDestinoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtIdTitularCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtIdCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(TxtIdCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblNumCheque))
                    .addComponent(TxtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImporteCheque)
                    .addComponent(TxtImporteCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblFechaCobro))
                    .addComponent(jDateFechaCobro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblTipoCheque))
                    .addComponent(jComboTipoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblEstadoDeCheque))
                    .addComponent(jComboEstadoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblObservacionCheque)
                    .addComponent(TxtObservacionCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaEntrega)
                    .addComponent(jDateFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboTitularCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitularCheque)
                    .addComponent(TxtIdTitularCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitularDestino)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboTitularDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TxtIdTitularDestinoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsoCheque)
                    .addComponent(TxtUsoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgregarCheque)
                    .addComponent(btnModificarCheque)
                    .addComponent(btnEliminarCheque)
                    .addComponent(btnLimpiarCheque)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarChequeActionPerformed
        if (TxtNumero.getText().equals("")) {
            Utilidades.msg(null, "El numero del cheque no puede estar vacio");
            TxtNumero.requestFocus();
            return;
        }
        
        if(Utilidades.isNunInt(TxtNumero.getText()) && !(Integer.parseInt(TxtNumero.getText()) > 0)){
           Utilidades.msg(null, "Numero incorrecto");
            TxtNumero.setText("");
            TxtNumero.requestFocus();
            return;
        }

        if (TxtImporteCheque.getText().equals("")) {
            Utilidades.msg(null, "El importe no puede estar vacio");
            TxtImporteCheque.requestFocus();
            return;
        }
        
        if(!Utilidades.isValidBigDecimal(TxtImporteCheque.getText())){
           Utilidades.msg(null, "Importe incorrecto");
            TxtImporteCheque.setText("");
            TxtImporteCheque.requestFocus();
            return;
        }

                    //EVALUAR FECHA DE COBRO TODO

        if (jComboTipoCheque.getSelectedItem().equals("--")) {
            Utilidades.msg(null, "El tipo de cheque no puede estar vacio");
            jComboTipoCheque.requestFocus();
            return;
        }

        
        
        if (jComboEstadoCheque.getSelectedItem().equals("--")) {
            Utilidades.msg(null, "El estado del cheque no puede estar vacio");
            jComboEstadoCheque.requestFocus();
            return;
        }
        
                    //EVALUAR FECHA DE ENTREGA TODO

                    
        

        if (Utilidades.existe(con.getConexion(), "SELECT (1) FROM cheque WHERE nro_cheque = " + Integer.parseInt(TxtNumero.getText()) + " ")) {
            Utilidades.msg(null, "No se puede ingresar porque el numero de cheque ya existe");
            TxtNumero.setText("");
            TxtIdCheque.setText("");
            TxtImporteCheque.setText("");
            jComboTipoCheque.setSelectedIndex(0);
            jComboEstadoCheque.setSelectedIndex(0);
            TxtObservacionCheque.setText("");
            jComboTitularCheque.setSelectedIndex(0);
            jComboTitularDestino.setSelectedIndex(0);
            TxtUsoCheque.setText("");
            jDateFechaCobro.setDate(null);
            jDateFechaEntrega.setDate(null);

        } else {
            try {
                Cheque cheque = new Cheque();
                cheque.setEstadoCheque(jComboEstadoCheque.getSelectedItem().equals("Cobrado") ? 1 : 0);
                cheque.setFechaCobroCheque(jDateFechaCobro.getDate());
                cheque.setTipoCheque(jComboTipoCheque.getSelectedItem().toString());
                cheque.setFechaEntregaCheque(jDateFechaEntrega.getDate());
                cheque.setImporteCheque(new BigDecimal(TxtImporteCheque.getText()));
                cheque.setNumCheque(Integer.parseInt(TxtNumero.getText()));
                cheque.setObservacionCheque(TxtObservacionCheque.getText());
                //cheque.setTitularCheque(Long.parseLong(TxtTitularCheque.getText()));
                //cheque.setTitularDestino(Long.parseLong(TxtTitularDestino.getText()));
                cheque.setUsoCheque(TxtUsoCheque.getText());

                daoCheque.ingresarCheque(cheque, con.getConexion());
                Utilidades.msg(null, "Cheque ingresado correctamente");
                TxtNumero.setText("");
                TxtImporteCheque.setText("");
                jDateFechaCobro.setDate(null);
                jComboTipoCheque.setSelectedIndex(0);
                jComboEstadoCheque.setSelectedIndex(0);
                TxtObservacionCheque.setText("");
                jDateFechaEntrega.setDate(null);
                jComboTitularCheque.setSelectedIndex(0);
                jComboTitularDestino.setSelectedIndex(0);
                TxtUsoCheque.setText("");

            } catch (SQLException ex) {
                Utilidades.msg(null, "Error al ingresar el Cheque");
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnAgregarChequeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCheques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCheques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCheques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCheques.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCheques().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtIdCheque;
    private javax.swing.JTextField TxtIdTitularCheque;
    private javax.swing.JTextField TxtIdTitularDestinoCheque;
    private javax.swing.JTextField TxtImporteCheque;
    private javax.swing.JTextField TxtNumero;
    private javax.swing.JTextField TxtObservacionCheque;
    private javax.swing.JTextField TxtUsoCheque;
    private javax.swing.JButton btnAgregarCheque;
    private javax.swing.JButton btnEliminarCheque;
    private javax.swing.JButton btnLimpiarCheque;
    private javax.swing.JButton btnModificarCheque;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboEstadoCheque;
    private javax.swing.JComboBox<String> jComboTipoCheque;
    private javax.swing.JComboBox<String> jComboTitularCheque;
    private javax.swing.JComboBox<String> jComboTitularDestino;
    private com.toedter.calendar.JDateChooser jDateFechaCobro;
    private com.toedter.calendar.JDateChooser jDateFechaEntrega;
    private javax.swing.JLabel lblEstadoDeCheque;
    private javax.swing.JLabel lblFechaCobro;
    private javax.swing.JLabel lblFechaEntrega;
    private javax.swing.JLabel lblImporteCheque;
    private javax.swing.JLabel lblNumCheque;
    private javax.swing.JLabel lblObservacionCheque;
    private javax.swing.JLabel lblTipoCheque;
    private javax.swing.JLabel lblTitularCheque;
    private javax.swing.JLabel lblTitularDestino;
    private javax.swing.JLabel lblUsoCheque;
    // End of variables declaration//GEN-END:variables
}
